export const SET_AUTH = {
    REQ_AUTH: 'REQ_AUTH',

    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
};

export const SET_AUTH_LOCAL_STORAGE = {
    REQ_AUTH_LOCAL_STORAGE: 'REQ_AUTH_LOCAL_STORAGE',
    REQ_REMOVE_AUTH_LOCAL_STORAGE: 'REQ_REMOVE_AUTH_LOCAL_STORAGE',
};
